In [1]:
import maurikit_learn as ml
import numpy as np
from sklearn.model_selection import train_test_split

# Dados

In [2]:
#Embaralha dados
dados = np.loadtxt("ex2data1.txt", delimiter=",")

#Embaralhando as amostras
np.random.shuffle(dados)

#Separa dados
X = dados[:,0:2]
y = dados[:,2]

#Normalização
X = (X - X.min()) / (X.max() - X.min())

#Separação de conjunto de treino e conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [3]:
X_train

array([[0.68605319, 0.55774797],
       [0.52584783, 0.44335673],
       [0.27252406, 0.3128091 ],
       [0.34273413, 0.8477762 ],
       [0.20939718, 0.5215962 ],
       [0.29238382, 0.65574989],
       [0.29348214, 0.26941736],
       [0.00326632, 0.19831398],
       [0.7019434 , 0.64907812],
       [0.85450448, 0.51226942],
       [0.71501627, 0.63214715],
       [0.71981433, 0.88946677],
       [0.2153456 , 0.37634961],
       [0.4610047 , 0.31535723],
       [0.74772195, 0.18147099],
       [0.14588236, 0.58921448],
       [0.38956944, 0.42218528],
       [0.58195856, 0.90109194],
       [0.53405404, 0.52359231],
       [0.72106391, 0.87289906],
       [0.65098907, 0.86522218],
       [0.69624872, 0.95441487],
       [0.37545302, 0.13190164],
       [0.53481039, 0.18317031],
       [0.67250409, 0.25107329],
       [0.60610945, 0.94839738],
       [0.03818328, 0.18988869],
       [0.97052763, 0.81223711],
       [0.86697331, 0.19108447],
       [1.        , 0.60643564],
       [0.

In [4]:
y_train

array([1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1.,
       1., 0.])

# Usando Gradiente Descendente

In [5]:
LRG = ml.LogisticRegression_GRAD()

In [6]:
LRG.fit(X_train, y_train, learning_rate=0.2, epochs=200)

[1. 1. 1.]
Coeficientes: [-1.39947745  1.71924608  2.07506457]


In [7]:
y_pred = LRG.predict(X_test)

### Acurácia

In [8]:
ml.acuracia(y_test, y_pred)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices