In [1]:
import maurikit_learn as ml
import numpy as np
from sklearn.model_selection import train_test_split

# Dados

In [2]:
#Embaralha dados
dados = np.loadtxt("ex2data1.txt", delimiter=",")

#Embaralhando as amostras
np.random.shuffle(dados)

#Separa dados
X = dados[:,0:2]
y = dados[:,2]

#Normalização
X = (X - X.min()) / (X.max() - X.min())

#Separação de conjunto de treino e conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [3]:
X_train

array([[0.14904504, 0.96713911],
       [0.86697331, 0.19108447],
       [0.74887421, 0.66538315],
       [0.74975856, 0.15134841],
       [0.29348214, 0.26941736],
       [0.58195856, 0.90109194],
       [0.44500891, 0.95246556],
       [0.96872217, 0.55616005],
       [0.86556634, 0.82343075],
       [0.05952839, 0.20282216],
       [0.53481039, 0.18317031],
       [0.55914951, 0.32509619],
       [0.46169753, 0.57182438],
       [0.30083445, 0.22594377],
       [1.        , 0.60643564],
       [0.63337365, 0.56996271],
       [0.64981247, 0.7983644 ],
       [0.91782133, 0.67508863],
       [0.43176427, 0.80622771],
       [0.2153456 , 0.37634961],
       [0.65098907, 0.86522218],
       [0.34273413, 0.8477762 ],
       [0.76581739, 0.26260164],
       [0.38956944, 0.42218528],
       [0.06542784, 0.68749511],
       [0.52584783, 0.44335673],
       [0.36235552, 0.49983657],
       [0.27989286, 0.42640877],
       [0.45537943, 0.28948781],
       [0.85450448, 0.51226942],
       [0.

In [4]:
y_train

array([1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1.])

# Usando Gradiente Descendente

In [5]:
LRG = ml.LogisticRegression_GRAD()

In [6]:
LRG.fit(X_train, y_train, learning_rate=0.2, epochs=200)

[1. 1. 1.]
Coeficientes: [-1.18520067  2.09548031  1.59165986]


In [7]:
y_pred = LRG.predict(X_test)

### Acurácia

In [8]:
ml.acuracia(y_test, y_pred)

0.7333333333333333